name: Deployment Pipeline

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simplePipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: cd guideme-backend && npm install && cd .. && cd guideme-frontend && npm install && cd ..
      - name: ESlint
        run: cd guideme-backend && npm run lint && cd ../guideme-frontend && npm run lint && cd .
      

      
