name: Deployment Pipeline

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simplePipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        # the "echo" command in the next line is a workaround for a bug in the dependecy tree caused by babel-jest
        # see more https://stackoverflow.com/a/57089043/12019806 
        run: npm ci && cd client && echo SKIP_PREFLIGHT_CHECK=true >> .env && npm ci cd ..  
      - name: Backend Test
        run: npm run test
        env:
          MONGODB_URI_TEST: ${{secrets.MONGODB_URI_TEST}}
          SECRET: ${{secrets.SECRET}}
      - name: ESlint
        run: npm run lint && cd client && npm run lint && cd ..
      - name: Build
        run: npm run build:ui

      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' }} 
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pure-headland-21885" 
          heroku_email: "mohamedabdelfatah2027@gmail.com"
          healthcheck: "https://pure-headland-21885.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true